# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BASTools
author: Matteo Bregola
email: matteobregola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the Breach and Attack Simulation (BAS) Tool Knowledge Base! Explore the latest in BAS technology,
   analysis frameworks, and top solutions to enhance your security strategy.
baseurl: "/BASTools" # the subpath of your site, e.g. /blog
url: "https://matteobregola.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  matteobregola
keywords: "BAS, Breach and Attack Simulation, BAS Tools, Automated Adversary Emulation, BAS Tool, Offensive security"

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default"
minimal_mistakes_skin2: "dark"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

include: ['pages', 'pages/framework']
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
